### ISSUE TITLE
Unable to find image '8000:80' locally docker: Error response from daemon: pull access denied for 8000, repository does not exist or may require 'docker login'.

### ISSUE THREAD

**Issue by qcode-1** [surveyjs/surveyjs-php#1]
This is the error i got when i run this 
"

sudo docker run --name appsrv --link dbsrv:dataserver-p 8000:80 -d -v Applications/XAMPP/xamppfiles/htdocs/Github/surveyjs-php/docker/surveyjs-php:var/www/site/ surveyjs-php

"

WHAT might be the problem?

**Comment by dmitry-kurmanov** [comment]
Hello! Do you complete all steps from the [README ](https://github.com/surveyjs/surveyjs-php#prerequisites)? You need to have installed and operable docker on your machine and build both docker images - for dbserver and for app server containers.
Could you provide us with additional information - OS you are using, docker version and error logs?
