### ISSUE TITLE
Convert example to MySQL?

### ISSUE THREAD

**Issue by brundles** [surveyjs/surveyjs-php#2]
Hi there - i can see your Postgresdb example, which is good.

Any pointers on how i can change this to be MySQL compliant instead? I believe the PHP/MySQL setup is much wider used than Postgres :)

Thank you for a super solution!

**Comment by dmitry-kurmanov** [comment]
Hello! Thanks for the interest! This is a sample project not a production ready boilerplate. We've implemented here a basic functionality to demonstrate SurveyJS service principles. We hope this will increase the interest in this project and encourages the community to elaborate this project further.
We'll take your suggestion into account in our work.
